config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins
  devise_for :users
  resources :tracks, except: [:show]

  root to: "home#index"
  get "home/index"
end

app/models/admin.rb
class Admin
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/models/track.rb
class Track  
  include Mongoid::Document
  include Mongoid::Timestamps
  belongs_to :user
  field :author, type: String
  field :name, type: String
  field :release_date, type: String
  field :image, type: String
  field :audio, type: String
  mount_uploader :audio, AudioUploader
  mount_uploader :image, ImageUploader
  validates :author, length: { maximum: 140 }, presence: true
validates :name, length: { maximum: 140 }, presence: true
validates :image, file_size: { less_than: 10.megabytes }
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
    # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many  :tracks
  ## Database authenticatable
  field :email,              type: String,  default: ""
  field :encrypted_password, type: String,  default: ""
  field :username,           type: String,  default: ""
  field :admin,              type: Boolean, default: false
  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?
 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!
  def index
    @tracks = Track.all #('created_at DESC') для сортировки
  end

  def new
    @track = Track.new
  end

  def create
    @track = current_user.tracks.new(track_params)

    if @track.save
      redirect_to tracks_path, notice: "The track #{@track.author} #{@track.name} has been added!" and return
    end
    render 'new'
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])

    if @track.update_attributes(track_params)
      redirect_to tracks_path, notice: "The track #{@track.author} #{@track.name} has been updated!" and return
    end

    render 'edit'
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    redirect_to tracks_path, notice: "The track #{@track.author} #{@track.name} has been deleted!" and return
  end
private
  def track_params
    params.require(:track).permit(:author, :name, :release_date, :image, :audio, :remove_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/home/index.html.erb
<h1 align="center">Audio uploader</h1>
<p align="center">Ваш загрузчик музыки</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin_panel</title>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid" style="background: whitesmoke">
     <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="/home/index">
        <img src="<%= asset_path("logotip.png") %>" width="40" height="40" alt="Opps!" />
      </a> 

      <div>
       <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link" href="/tracks">Трэки</a></li>
                <li class="nav-item"><% if user_signed_in? %>
         Hello,  <%= current_user.username %> | <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
          
          <% else %>
          <%= link_to 'Войти в uploader', new_user_session_path %>
          
        <%end%></li>
       </ul> 
      </div>
      


       
    </nav> 
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <h3>Some errors were found:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_form.html.erb
<% if track.image? %>
    <%= image_tag track.image.url %>
    <div>
      <%= label_tag :remove_image do %>
        Remove image
        <%= f.check_box :remove_image %>
      <% end %>
    </div>
<% end %>

app/views/tracks/_form.html.erb
<%= render 'shared/errors', object: @track %>
<%= form_with model: @track, local: true do |f| %>
  <div class="form-group">
    <%= f.label :Исполнитель %>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Название_трэка %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Предпологаемая_дата_релиза %>
    <%= f.date_field :release_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Обложка %>
    <%= f.file_field :image, class: "form-control" %>
    <%= f.label :Удалить_обложку %>
    <%= f.check_box :remove_image %>
  </div>
  <div class="form-group">
    <%= f.label :Аудио %>
    <%= f.file_field :audio, class: "form-control" %>
  </div>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/tracks/create.html.erb
<h1>Tracks#create</h1>
<p>Find me in app/views/tracks/create.html.erb</p>

app/views/tracks/destroy.html.erb
<h1>Tracks#destroy</h1>
<p>Find me in app/views/tracks/destroy.html.erb</p>

app/views/tracks/edit.html.erb
<h1>New track</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/tracks/index.html.erb
<h1>Tracks</h1>
<div class="well">
  <%= link_to "New track", new_track_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-borderless">
  <thead>
    <tr>
      <th>Исполнитель</th>
      <th>Название трэка</th>
      <th>Предпологаемая дата релиза</th>
      <th>Обложка</th>
      <th>Файл</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @tracks.size == 0 %>
      <tr>
        <td colspan="6">No tracks found.</td>
      </tr>
    <% else %>
      <% @tracks.where(user_id: current_user).each do |track| %>
        <tr>
          <td><%= track.author %></td>
          <td><%= track.name %></td>
          <td><%= track.release_date.split('-', 3).reverse.join('-') %></td>
          <td><img src="<%= track.image.url %>" height="150px" width="150px" alt=" " />
           <!-- <%= image_tag(track.image.url, alt: 'Image') if track.image? %> --> </td>
          <td>
            <audio controls src="<%= track.audio.url %>"></audio>         
         </td>
          <td><%= link_to "Edit", edit_track_path(track), class: "btn btn-default" %>
          </td>
          <td><%= button_to "Delete", track, method: :delete, data: { confirm: "Are you sure you wish to delete #{track.author} #{track.name}?" }, class: "btn btn-danger" %>
           </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tracks/new.html.erb
<h1>New track</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/tracks/update.html.erb
<h1>Tracks#update</h1>
<p>Find me in app/views/tracks/update.html.erb</p>